/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package version1;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lung
 */
public class DeskTopWatch extends javax.swing.JFrame implements Runnable{
    int hour, minute, second;
    static int milisecond1 = 0;
    static int second1 = 0;
    static int minute1 = 0;
    static int hour1 = 0;
    static boolean state = true;
 
    /**
     * Creates new form DeskTopWatch
     */
    public DeskTopWatch() {
        // Set time clock
        initComponents();
        Thread thread = new Thread(this);
        thread.start();
        //Set day 
        String pattern = "EEEE,  dd - MM - yyyy";
        SimpleDateFormat dateformat = new SimpleDateFormat(pattern,new Locale("vi","VN"));
        dayDisplay.setText(dateformat.format(new Date()));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuBar = new javax.swing.JPanel();
        GioQuocTeButton = new javax.swing.JButton();
        BamGioButton = new javax.swing.JButton();
        HenGioButton = new javax.swing.JButton();
        BaoThucButton = new javax.swing.JButton();
        XemGioButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        gioQuocTePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        baoThucPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bamGioPanel = new javax.swing.JPanel();
        hourOfStop = new javax.swing.JLabel();
        secondOfStop = new javax.swing.JLabel();
        milisecondStop = new javax.swing.JLabel();
        minuteOfStop = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        xemNgayGioPanel = new javax.swing.JPanel();
        hourDisplay = new javax.swing.JLabel();
        dayDisplay = new javax.swing.JLabel();
        HenGioPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DesktopWatch");
        setSize(new java.awt.Dimension(1200, 800));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        menuBar.setBackground(new java.awt.Color(255, 204, 255));

        GioQuocTeButton.setText("Giờ Quốc Tế");
        GioQuocTeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GioQuocTeButtonActionPerformed(evt);
            }
        });

        BamGioButton.setText("Bấm Giờ");
        BamGioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BamGioButtonActionPerformed(evt);
            }
        });

        HenGioButton.setText("Hẹn Giờ");
        HenGioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HenGioButtonActionPerformed(evt);
            }
        });

        BaoThucButton.setText("Báo Thức");
        BaoThucButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaoThucButtonActionPerformed(evt);
            }
        });

        XemGioButton.setText("Xem Ngày Giờ");
        XemGioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XemGioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GioQuocTeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BamGioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(HenGioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(XemGioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(BaoThucButton, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(GioQuocTeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BaoThucButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BamGioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(HenGioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(XemGioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        gioQuocTePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Giờ Quốc Tế");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout gioQuocTePanelLayout = new javax.swing.GroupLayout(gioQuocTePanel);
        gioQuocTePanel.setLayout(gioQuocTePanelLayout);
        gioQuocTePanelLayout.setHorizontalGroup(
            gioQuocTePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gioQuocTePanelLayout.createSequentialGroup()
                .addGroup(gioQuocTePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gioQuocTePanelLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gioQuocTePanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        gioQuocTePanelLayout.setVerticalGroup(
            gioQuocTePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gioQuocTePanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", gioQuocTePanel);

        baoThucPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Báo Thức");

        javax.swing.GroupLayout baoThucPanelLayout = new javax.swing.GroupLayout(baoThucPanel);
        baoThucPanel.setLayout(baoThucPanelLayout);
        baoThucPanelLayout.setHorizontalGroup(
            baoThucPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baoThucPanelLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );
        baoThucPanelLayout.setVerticalGroup(
            baoThucPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baoThucPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", baoThucPanel);

        bamGioPanel.setBackground(new java.awt.Color(255, 255, 255));

        hourOfStop.setBackground(new java.awt.Color(204, 204, 204));
        hourOfStop.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        hourOfStop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hourOfStop.setText("00 :");
        hourOfStop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        secondOfStop.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        secondOfStop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondOfStop.setText("00 :");
        secondOfStop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        milisecondStop.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        milisecondStop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        milisecondStop.setText("00 :");
        milisecondStop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        minuteOfStop.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        minuteOfStop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minuteOfStop.setText("00 :");
        minuteOfStop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Stop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bamGioPanelLayout = new javax.swing.GroupLayout(bamGioPanel);
        bamGioPanel.setLayout(bamGioPanelLayout);
        bamGioPanelLayout.setHorizontalGroup(
            bamGioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bamGioPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(hourOfStop, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(minuteOfStop, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(secondOfStop, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(milisecondStop, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(bamGioPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        bamGioPanelLayout.setVerticalGroup(
            bamGioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bamGioPanelLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(bamGioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondOfStop, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuteOfStop, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourOfStop, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(milisecondStop, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bamGioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bamGioPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bamGioPanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(bamGioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", bamGioPanel);

        xemNgayGioPanel.setBackground(new java.awt.Color(255, 255, 255));

        hourDisplay.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        hourDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hourDisplay.setText("Hour");

        dayDisplay.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        dayDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayDisplay.setText("Ngày và giờ");

        javax.swing.GroupLayout xemNgayGioPanelLayout = new javax.swing.GroupLayout(xemNgayGioPanel);
        xemNgayGioPanel.setLayout(xemNgayGioPanelLayout);
        xemNgayGioPanelLayout.setHorizontalGroup(
            xemNgayGioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xemNgayGioPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(xemNgayGioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hourDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(xemNgayGioPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(dayDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        xemNgayGioPanelLayout.setVerticalGroup(
            xemNgayGioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xemNgayGioPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(hourDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dayDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("", xemNgayGioPanel);

        HenGioPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Hẹn giờ");

        jLabel1.setText("time");

        javax.swing.GroupLayout HenGioPanelLayout = new javax.swing.GroupLayout(HenGioPanel);
        HenGioPanel.setLayout(HenGioPanelLayout);
        HenGioPanelLayout.setHorizontalGroup(
            HenGioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HenGioPanelLayout.createSequentialGroup()
                .addGroup(HenGioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HenGioPanelLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HenGioPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HenGioPanelLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        HenGioPanelLayout.setVerticalGroup(
            HenGioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HenGioPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", HenGioPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(menuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(860, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void XemGioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XemGioButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_XemGioButtonActionPerformed

    private void GioQuocTeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GioQuocTeButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_GioQuocTeButtonActionPerformed

    private void BaoThucButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaoThucButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_BaoThucButtonActionPerformed

    private void BamGioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BamGioButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_BamGioButtonActionPerformed

    private void HenGioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HenGioButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_HenGioButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        state = true;
        Thread t = new Thread(){
            @Override
            public void run() {
               for(;;){
               
                   if(state == true){
                       try {
                           sleep(1);
                           if(milisecond1 > 1000){
                               milisecond1 = 0;
                               second1++;
                           }
                           if(second1 > 60){
                               milisecond1 = 0;
                               second1 = 0;
                               minute1++;
                           }
                           if(minute1 > 60){
                               milisecond1 = 0;
                               second1 = 0;
                               minute1 = 0;
                               hour1++;
                           }
                           milisecondStop.setText(milisecond1 + "");
                           secondOfStop.setText(second1 + " : ");
                           minuteOfStop.setText(minute1 + " : ");
                           hourOfStop.setText(hour1 + " : ");
                           milisecond1++;
                       } catch (Exception e) {
                       }
                   }
                   else{
                       break;
                   }
               }
            }
            
        };
        t.start();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        state = false;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        state = false;
        hour1 = 0;
        minute1 = 0;
        second1 = 0;
        milisecond1 = 0;
        hourOfStop.setText("00 : ");
        minuteOfStop.setText("00 : ");
        secondOfStop.setText("00  : ");
        milisecondStop.setText("00");
    }//GEN-LAST:event_jButton3ActionPerformed

     
        
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeskTopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeskTopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeskTopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeskTopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeskTopWatch().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BamGioButton;
    private javax.swing.JButton BaoThucButton;
    private javax.swing.JButton GioQuocTeButton;
    private javax.swing.JButton HenGioButton;
    private javax.swing.JPanel HenGioPanel;
    private javax.swing.JButton XemGioButton;
    private javax.swing.JPanel bamGioPanel;
    private javax.swing.JPanel baoThucPanel;
    private javax.swing.JLabel dayDisplay;
    private javax.swing.JPanel gioQuocTePanel;
    private javax.swing.JLabel hourDisplay;
    private javax.swing.JLabel hourOfStop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel menuBar;
    private javax.swing.JLabel milisecondStop;
    private javax.swing.JLabel minuteOfStop;
    private javax.swing.JLabel secondOfStop;
    private javax.swing.JPanel xemNgayGioPanel;
    // End of variables declaration//GEN-END:variables

   
    public void run() {
        
        while(true ){
            Calendar calendar = Calendar.getInstance();
            hour = calendar.get(Calendar.HOUR_OF_DAY);
            minute = calendar.get(Calendar.MINUTE);
	    second = calendar.get(Calendar.SECOND);
            SimpleDateFormat sdf = new SimpleDateFormat("HH   :   mm   :   ss");
            Date date = calendar.getTime();
            String time24 = sdf.format(date);
            hourDisplay.setText(time24);
 
        }
        
    }
}
